name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '17.x'

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
            
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2
          run_install: true
      
      - name: Install & Test
        run: |
          pnpm install
          pnpm test
